Show time of day
PureBhaktiArchive/archive-web-app pull request #41
Opened 2021-06-04 06:02 UTC by gauraraj

https://trello.com/c/1LbANDeF/142-show-time-of-day

2021-06-06 15:10 UTC, gauraraj reviewed
Show time of day with Prettier check

2021-06-06 15:25 UTC, anantakrishna requested changes

2021-06-06 15:25 UTC, anantakrishna commented on frontend/src/index.html
> +                        <span title="time-of-day">{{timeOfDay}}</span>
The title should be for humans. See the titles on other elements.

2021-06-06 15:31 UTC, gauraraj reviewed
Changed to language readable by humans

2021-06-07 05:42 UTC, anantakrishna approved these changes

2021-06-07 05:42 UTC, merged